package com.ancientmc.acp.task;

import com.ancientmc.acp.util.AcpException;
import com.ancientmc.acp.util.Paths;
import org.apache.commons.io.FileUtils;
import org.gradle.api.Project;

import java.io.File;
import java.io.FileFilter;
import java.io.IOException;
import java.util.List;
import java.util.Map;

/**
 * Cleans the workspace. This only deletes files generated by decompiling and mod building.
 * @author moist-mason
 */
public abstract class Clean extends AcpTask {
    private static final FileFilter SRC_FILTER = (File file) -> !file.getName().equals("acp");
    private static final FileFilter TEMP_FILTER = (File file1) -> !file1.getName().equals("client.jar") && !file1.getName().endsWith(".json");
    private static final FileFilter RUN_FILTER = (File file2) -> !file2.getName().contains("resources") && !file2.getName().contains("bin");

    @Override
    public void action(final Project project) {
        getUnfilteredPaths().forEach(path -> {
            try {
                File[] files = project.file(path).listFiles();

                if (files != null) {
                    deleteFiles(path, files);
                }
            } catch (IOException e) {
                throw new AcpException(e.getMessage(), logger, e);
            }
        });

        getFilteredPaths().forEach((path, filter) -> {
            try {
                File[] files = project.file(path).listFiles(filter);

                if (files != null) {
                    deleteFiles(path, files);
                }
            } catch (IOException e) {
                throw new AcpException(e.getMessage(), logger, e);
            }
        });
    }

    public void deleteFiles(String path, File[] files) throws IOException {
        if (files.length > 0) {
            logger.toConsole("Deleting {} files in path " + path, Integer.toString(files.length));
        }

        for (File file : files) {
            delete(file);
        }
    }

    public void delete(File file) throws IOException {
        logger.toFile("Delete -> {}", file.getAbsolutePath());

        if (file.isDirectory()) {
            FileUtils.deleteDirectory(file);
        } else {
            FileUtils.delete(file);
        }

        if (!file.exists()) {
            logger.toFile("Deleted");
        }
    }

    /** @return a list of every path whose contents will be entirely deleted. */
    public static List<String> getUnfilteredPaths() {
        return List.of(Paths.DIR_RESOURCES, Paths.DIR_BUILD_MODDED);
    }

    /**
     * For some paths we want to only delete certain files or directories, not the whole thing. This calls a map where
     * the key is a directory path, and its value is the corresponding file filter that only lets us use what we want to
     * keep.
     * @return The inputs.
     */
    public static Map<String, FileFilter> getFilteredPaths() {
        return Map.of(Paths.DIR_SRC, SRC_FILTER,
                Paths.DIR_TEMP, TEMP_FILTER,
                Paths.DIR_RUN, RUN_FILTER);
    }
}
