package com.ancientmc.acp.task;

import com.ancientmc.acp.util.Paths;
import org.apache.commons.io.FileUtils;
import org.gradle.api.Project;
import org.gradle.api.tasks.TaskAction;

import java.io.File;
import java.io.FileFilter;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Cleans the workspace. This only deletes files generated by decompiling and mod building,
 * @author moist-mason
 */
public abstract class Clean extends AcpTask {
    private static final FileFilter SRC_FILTER = (File file) -> !file.getAbsolutePath().contains("acp" + File.separator + "client");
    private static final FileFilter TEMP_FILTER = (File file1) -> !file1.getName().equals("client.jar") && !file1.getName().endsWith(".json");
    private static final FileFilter RUN_FILTER = (File file2) -> !file2.getName().contains("resources") && !file2.getName().contains("bin");

    @TaskAction
    public void exec() {
        Project project = getProject();

        getUnfilteredPaths().forEach(path -> {
            try {
                File[] files = project.file(path).listFiles();
                deleteFiles(project, files);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        });

        getFilteredPaths().forEach((path, filter) -> {
            try {
                File[] files = project.file(path).listFiles(filter);
                deleteFiles(project, files);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        });
    }

    public void deleteFiles(Project project, File[] files) throws IOException {
        if (files != null) {
            for (File file : files) {
                delete(project, file);
            }
        }
    }

    public void delete(Project project, File file) throws IOException {
        logger.file(project, "Delete -> {}", file.getAbsolutePath());

        if (file.isDirectory()) {
            FileUtils.deleteDirectory(file);
        } else {
            FileUtils.delete(file);
        }
    }

    /**
     * @return a list of every path whose content will be entirely deleted.
     */
    public static List<String> getUnfilteredPaths() {
        return List.of(
                Paths.DIR_RESOURCES,
                "build/modding/"
        );
    }

    /**
     * For some paths we want to only delete certain files or directories. This calls a map where the key is a directory path,
     * and its value is the corresponding file filter that only lets us use what we want to keep.
     * @return The inputs.
     */
    public static Map<String, FileFilter> getFilteredPaths() {
        Map<String, FileFilter> inputs = new HashMap<>();
        inputs.put(Paths.DIR_SRC, SRC_FILTER);
        inputs.put(Paths.DIR_TEMP, TEMP_FILTER);
        inputs.put(Paths.DIR_RUN, RUN_FILTER);

        return inputs;
    }
}
