buildscript {
    repositories {
        mavenCentral()
        maven { url = 'https://github.com/ancientmc/ancientmc-maven/raw/maven' }
    }
    dependencies {
        classpath 'io.github.moist-mason:license-importer:1.0'
    }
}

plugins {
    id 'java-library'
    id 'java-gradle-plugin'
    id 'maven-publish'
}

group 'io.github.ancientmc' // Usual
version '0.2.1.' + new Date().format('yyyyMMdd.HHmmss') + '-BETA'

java.toolchain.languageVersion = JavaLanguageVersion.of(8)

repositories {
    mavenCentral()
    mavenLocal()
    maven { url = 'https://maven.neoforged.net/'}
}

apply plugin: 'io.github.moist-mason.license-importer'

licenseimporter {
    url = 'https://raw.githubusercontent.com/ancientmc/license/master/LICENSE'
    output = file(project.projectDir.path + "/LICENSE")
}

sourceSets {
    acp
    modtools
}

configurations {
    acpImplementation
    modtoolsImplementation.extendsFrom acpImplementation
    implementation.extendsFrom acpImplementation, modtoolsImplementation
}

dependencies {
    acpImplementation gradleApi()
    acpImplementation 'com.google.code.gson:gson:2.11.0'
    acpImplementation 'commons-io:commons-io:2.18.0'
    acpImplementation 'net.neoforged:srgutils:1.0.9'
    acpImplementation 'org.apache.commons:commons-compress:1.27.1'

    modtoolsImplementation sourceSets.acp.output

    testImplementation gradleTestKit()
    testImplementation 'org.junit.jupiter:junit-jupiter:5.9.2'
}

gradlePlugin {
    website = 'https://github.com/ancientmc/acp-gradle'
    vcsUrl = 'https://github.com/ancientmc/acp-gradle'
    plugins {
        acp {
            id = 'com.ancientmc.acp'
            displayName = 'acp-gradle'
            description = 'Gradle plugin for Ancient Coder Pack (ACP) processes.'
            implementationClass = 'com.ancientmc.acp.AcpPlugin'
        }
    }
}

jar {
    from sourceSets.acp.output
    from sourceSets.modtools.output
    manifest {
        attributes(
                'Specification-Title': 'ACP Gradle',
                'Specification-Ventor': 'AncientMC',
                'Specification-Version': archiveVersion,
                'Implementation-Title': 'io.github.ancientmc:acp-gradle',
                'Implementation-Vendor': 'AncientMC',
                'Implementation-Version': archiveVersion,
        )
    }
}

tasks.register('testJar', Copy) {
    dependsOn jar
    from jar
    into('acp_test/plugins/')
    rename { 'acp.jar' }
}

tasks.named('test') {
    dependsOn testJar
    useJUnitPlatform()
    filter { includeTestsMatching '*testDecompileRuby' }
}

tasks.withType(Test).configureEach {
    testLogging {
        showStandardStreams true
    }
}

publishing {
    publications {
        pluginMaven(MavenPublication) {
            groupId = project.group
            artifactId = 'acp-gradle'
            version = project.version
            pom {
                name = 'acp-gradle'
                description = 'Gradle plugin for Ancient Coder Pack (ACP) processes.'
                url = 'https://github.com/ancientmc/acp-gradle'
                licenses {
                    license {
                        name = 'AncientMC License'
                        url = 'https://github.com/ancientmc/license/blob/master/LICENSE'
                    }
                }
                developers {
                    developer {
                        id = 'moist-mason'
                        name = 'Mason'
                    }
                }
            }
        }
    }
    repositories {
        maven {
            name = 'ancientmc-maven'
            url = '../ancientmc-maven/'
        }
    }
}