plugins {
    id 'java-library'
    id 'java-gradle-plugin'
    id 'maven-publish'
    id 'io.github.moist-mason.license-importer' version '1.0'
}

group 'com.ancientmc'
version '0.2.1.' + new Date().format('yyyyMMdd.HHmmss') + '-BETA'

java.toolchain.languageVersion = JavaLanguageVersion.of(8)

repositories {
    mavenCentral()
    mavenLocal()
    maven { url = 'https://maven.neoforged.net/' }
}

licenseimporter {
    url = 'https://raw.githubusercontent.com/ancientmc/license/master/LICENSE'
    output = file(project.projectDir.path + "/LICENSE")
}

sourceSets {
    acp
}

configurations {
    acpImplementation
}

dependencies {
    acpImplementation gradleApi()
    acpImplementation 'com.google.code.gson:gson:2.11.0'
    acpImplementation 'commons-io:commons-io:2.18.0'
    acpImplementation 'net.neoforged:srgutils:1.0.9'
    acpImplementation 'org.apache.commons:commons-compress:1.27.1'

    testImplementation gradleTestKit()
    testImplementation 'commons-io:commons-io:2.18.0'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.9.2'
}

gradlePlugin {
    website = 'https://github.com/ancientmc/acp-gradle'
    vcsUrl = 'https://github.com/ancientmc/acp-gradle'
    plugins.register('acp') {
        id = 'com.ancientmc.acp'
        displayName = 'acp-gradle'
        description = 'Gradle plugin for Ancient Coder Pack (ACP) processes.'
        implementationClass = 'com.ancientmc.acp.AcpPlugin'
    }
}

jar {
    from sourceSets.acp.output
    manifest {
        attributes(
                'Specification-Title': 'ACP Gradle',
                'Specification-Ventor': 'AncientMC',
                'Specification-Version': archiveVersion,
                'Implementation-Title': 'com.ancientmc:acp-gradle',
                'Implementation-Vendor': 'AncientMC',
                'Implementation-Version': archiveVersion,
        )
    }
}

tasks.register('testJar', Copy) {
    dependsOn jar
    from jar
    into('acp_test/plugins/')
    rename { 'acp.jar' }
}

test {
    dependsOn testJar
    useJUnitPlatform()
    filter { includeTestsMatching '*testDecompileAll' }
}

tasks.withType(Test).configureEach {
    testLogging {
        showStandardStreams true
    }
}

publishing {
    publications.register('pluginMaven', MavenPublication) {
        groupId = project.group
        artifactId = 'acp-gradle'
        version = project.version
        pom {
            name = 'acp-gradle'
            description = 'Gradle plugin for Ancient Coder Pack (ACP) processes.'
            url = 'https://github.com/ancientmc/acp-gradle'
            licenses {
                license {
                    name = 'AncientMC License'
                    url = 'https://github.com/ancientmc/license/blob/master/LICENSE'
                }
            }
            developers {
                developer {
                    id = 'moist-mason'
                    name = 'Mason'
                }
            }
            scm {

            }
        }
    }
    repositories {
        maven {
            name = 'ancientmc-maven'
            url = '../ancientmc-maven/'
        }
    }
}