[versions]
commons-compress = "1.27.1"
commons-io = "2.19.0"
gson = "2.13.0"
srgutils = "1.0.10"

[libraries]
commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commons-compress" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
srgutils = { module = "net.neoforged:srgutils", version.ref = "srgutils" }


