[versions]
commons-compress = "1.28.0"
commons-io = "2.21.0"
gson = "2.13.2"
srgutils = "1.0.11"
junit = "6.0.1"

[libraries]
commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commons-compress" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
srgutils = { module = "net.neoforged:srgutils", version.ref = "srgutils" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }

