buildscript {
    repositories {
        mavenCentral()
        maven { url = 'https://maven.neoforged.net/releases/' }
    }
    dependencies {
        classpath files('../../plugin/acp.jar')
    }
}

plugins {
    id 'java-library'
}

repositories {
    maven { url = 'https://libraries.minecraft.net/' }
    maven { url = 'https://maven.neoforged.net/releases/' }
    maven { url = 'https://github.com/ancientmc/ancientmc-maven/raw/maven/' }
}

sourceSets {
    main
}

apply plugin: 'com.ancientmc.acp'

import com.ancientmc.acp.util.*

version = '0.0.1'

acp {
    data = "com.ancientmc:versions:${minecraft_version}"
    loader = "{loader}"
    modName = 'ruby'
}

// These are easy ways to run tasks as opposed to CLI or finding them in your IDE's menus.
tasks.named('decompile')
tasks.named('downloadModLoader')
tasks.named('runClient')
tasks.named('buildMod')

tasks.register('injectModSrc', Copy) {
    from files('ruby/src/main/java/')
    into file('src/main/java/')
}

tasks.register('injectModResources', Copy) {
    from files('ruby/src/main/resources/')
    into file('src/main/resources/')
}

tasks.register('injectMod') { dependsOn (injectModSrc, injectModResources) }
