buildscript {
    repositories {
        mavenCentral()
        maven { url = 'https://maven.neoforged.net' }
    }
    dependencies {
        classpath files('../../plugins/acp.jar')
        classpath 'com.google.code.gson:gson:2.13.0'
        classpath 'commons-io:commons-io:2.19.0'
        classpath 'net.neoforged:srgutils:1.0.10'
        classpath 'org.apache.commons:commons-compress:1.27.1'
    }
}

plugins {
    id 'java-library'
}

repositories {
    maven { url = 'https://libraries.minecraft.net' }
    maven { url = 'https://maven.neoforged.net/' }
    maven { url = 'https://github.com/ancientmc/ancientmc-maven/raw/maven/' }
}

sourceSets {
    main
}

apply plugin: 'com.ancientmc.acp'

import com.ancientmc.acp.util.*

version = '0.0.1'

acp {
    data = "com.ancientmc:versions:${minecraft_version}"
    loader = "{loader}"
    modName = 'ruby'
}

// These are easy ways to run tasks as opposed to CLI or finding them in your IDE's menus.
tasks.named('decompile')
tasks.named('downloadModLoader')
tasks.named('runClient')
tasks.named('buildMod')

tasks.register('injectMod') {
    def files = files('mod_files').asFileTree
    files.each { file ->
        project.copy {
            def type = 'src/main/' + file.name.endsWith('.java') ? 'java/' : 'resources/'
            def parent = project.file('mod_files/' + type).toPath().relativize(file.parentFile.toPath()).toString().replace(File.separator, '/')
            from (file.absolutePath)
            into (project.file(type + '/' + parent))
        }
    }
}